// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCik6WVrD9FNWEFLn5vmOVQoK67KqWtGI0',
    appId: '1:1073368132770:web:302ccecb370019ac54fbfb',
    messagingSenderId: '1073368132770',
    projectId: 'underlimit-5fbad',
    authDomain: 'underlimit-5fbad.firebaseapp.com',
    storageBucket: 'underlimit-5fbad.firebasestorage.app',
    measurementId: 'G-KVJLPZHGQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD14D5lrLhDxgZHxuncFhjXYJx4MYWq3jM',
    appId: '1:1073368132770:android:7965e6af68eea13d54fbfb',
    messagingSenderId: '1073368132770',
    projectId: 'underlimit-5fbad',
    storageBucket: 'underlimit-5fbad.firebasestorage.app',
  );
}
